export const  ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const  ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const  ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
export const  CLEAR_ERRORS = "CLEAR_ERRORS"


export const  ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const  ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const  ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"

export const  PRODUCT_DETAILS_REQUEST = "ALL_PRODUCT_REQUEST"
export const  PRODUCT_DETAILS_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const  PRODUCT_DETAILS_FAIL = "ALL_PRODUCT_FAIL"